export { default as home } from './home.vue'
export { default as avatar } from './avatar.vue'
export { default as exit } from './exit.vue'
export { default as close } from './close.vue'
export { default as arrow } from './arrow.vue'
export { default as triangle } from './triangle.vue'
